const Districts = [
    'colombo',
    'gampaha',
    'kalutara',
    'kandy',
    'matale',
    'nuwaraEliya',
    'galle',
    'matara',
    'hambantota',
    'jaffna',
    'kilinochchi',
    'mannar',
    'vavuniya',
    'mullaitivu',
    'batticaloa',
    'ampara',
    'trincomalee',
    'kurunegala',
    'puttalam',
    'anuradhapura',
    'polonnaruwa',
    'badulla',
    'moneragala',
    'ratnapura',
    'kegalle'
]
export default Districts